### ISSUE TITLE
build fails with boost errors

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#3]
Which version of boost should be installed?  I currently have 

Version: 1.58.0.1ubuntu1

on Ubuntu 16.04 (installed via apt install libboost-all-dev)

[  1%] Building CUDA object CMakeFiles/voxelyze.3.0.dir/src/VX3/VX3_SimulationManager.cu.o
In file included from /home/rieffelj/src/voxcraft-sim/src/VX3/VX3_SimulationManager.cu:2:0:
/home/rieffelj/src/voxcraft-sim/src/Utils/ctool.h:11:29: fatal error: boost/process.hpp: No such file or directory
compilation terminated.
CMakeFiles/voxelyze.3.0.dir/build.make:160: recipe for target 'CMakeFiles/voxelyze.3.0.dir/src/VX3/VX3_SimulationManager.cu.o' failed
make[2]: *** [CMakeFiles/voxelyze.3.0.dir/src/VX3/VX3_SimulationManager.cu.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'CMakeFiles/voxelyze.3.0.dir/all' failed
make[1]: *** [CMakeFiles/voxelyze.3.0.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jrieffel** [comment]
update: i installed the latest version of boost from source (1.73) and now get a new error which makes me think voxcraft-sim requires an earlier version of boost:

[  1%] Building CUDA object CMakeFiles/voxelyze.3.0.dir/src/VX3/VX3_Collision.cu.o
/usr/include/boost/system/error_code.hpp: In function ‘constexpr bool boost::system::detail::failed_impl(int, const boost::system::error_category&)’:
/usr/include/boost/system/error_code.hpp:425:1: error: expression ‘boost::system::error_category::failed’ is not a constant-expression

**Comment by davidmatthews1uvm** [comment]
I was able to compile using boost 1.65.1 (on ubuntu 18.04.4) and boost 1.67.0 (RHEL 7). I am not sure what specific range of boost versions the code currently supports but either of the above should work.

**Comment by liusida** [comment]
Mine is 1.66/1.67 (on ubuntu 19.10)

**Comment by jrieffel** [comment]
Okay, I was able to compile and run with 1.65.1 installed.  Thanks!

**Comment by liusida** [comment]
And we updated the README, thanks

**Comment by davidmatthews1uvm** [comment]
Thanks for helping us improve our docs.
